const fs = require('fs')
const path = require('path')
const glob = require('glob');

/**
 * To omit problem with incorrect gas calculation gas field,
 * generated by brownie is removed from abi's fields manually
 * 
 * @param {abi_field} description 
 * @returns abi_field
 */
function delete_gas(abi_field) {
  if(abi_field.type === "function" && abi_field.gas) {
    abi_field.gas = undefined;
  }

 return abi_field
}


/**
 * Remove gas property from contract abi
 * @param {contractJSON} contractJSON 
 * @returns contractJSON
 */ 
 function prepare_contract_json(contractJSON) {
  const contractMeta = JSON.parse(contractJSON);
  const { abi, ...rest } = contractMeta;
  
  const preparedAbi = prepare_contract_abi(abi)

  return JSON.stringify({ abi: preparedAbi, ...rest }, null, 2)
}

function prepare_contract_abi(abi) {
  
  const preparedAbi = abi.map(description => {
    description = delete_gas(description)
    
    return description
  })

  return preparedAbi
}

module.exports = {
  prepare_contract_abi,
  prepare_contract_json
}